### ISSUE TITLE
[FEATURE] cache reactjs

### ISSUE THREAD

**Issue by eatmyvenom** [eatmyvenom/browserr#100]
## Wanted Behavior
What I would like to see is react in the cache for the app

This would also have to go with Babel is jsx is included

**Comment by eatmyvenom** [comment]
Actually no with Babel and stuff because that introduces overhead that they should deal with if they are using this

**Comment by eatmyvenom** [comment]
The react lib should be available

**Comment by venomsOther** [comment]
files
 
```
React: https://unpkg.com/react@16/umd/react.production.min.js
ReactDOM: https://unpkg.com/react-dom@16/umd/react-dom.production.min.js
```

**Comment by venomsOther** [comment]
no native jsx support yet

**Comment by venomsOther** [comment]
jsx would be `https://unpkg.com/babel-standalone@6/babel.min.js`

**Comment by venomsOther** [comment]
`https://unpkg.com/@babel/standalone/babel.min.js` okay maybe because it has native typescript, jsx and stuff

**Comment by eatmyvenom** [comment]
jsx is done

**Comment by eatmyvenom** [comment]
I think this is done, it at least in the code so closing the issue
