### ISSUE TITLE
[FEATURE] cache Vue js

### ISSUE THREAD

**Issue by eatmyvenom** [eatmyvenom/browserr#101]
## Current Behavior
Currently the applications behavior is to only have issues for react

## Wanted Behavior
What I would like to see is vue.js support as well

```NodeJS version : 12.0.0; ElectronJS version : 5.0.1; Browserr version : 1.2.0;```

**Comment by venomsOther** [comment]
urls
```
Router : https://unpkg.com/vue-router/dist/vue-router.js
Vue : https://unpkg.com/vue/dist/vue.js
```

**Comment by eatmyvenom** [comment]
done
