### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by venomsOther** [eatmyvenom/browserr#6]
## Current Behavior
Currently the maximize button is not rounded enough and does not align the bottom line with the minimize button This is not only slightly bothersome but also contrubutes to a poor feeling UI/UX

## Wanted Behavior
Consider going through all icons and changing them. If that is simply too much work, look into icon packs that are good for this application.

```NodeJS version : 11.1.0; ElectronJS version : 4.0.7; Browserr version : 1.0.0;```

**Comment by venomsOther** [comment]
Another thing is there should be multiple available icon packs and users can select

**Comment by eatmyvenom** [comment]
Font awesome works, google works
