### ISSUE TITLE
[FEATURE] site package

### ISSUE THREAD

**Issue by eatmyvenom** [eatmyvenom/browserr#87]
## Current Behavior
Currently the applications behavior is to access and use sites 

## Wanted Behavior
What I would like to see is a way to package an app for the current platform as it's own application using electron-packager

```NodeJS version : 12.0.0; ElectronJS version : 5.0.1; Browserr version : 1.2.0;```

**Comment by eatmyvenom** [comment]
use electron-packager

**Comment by eatmyvenom** [comment]
This could just be a drop in thing to the webview component but it needs to write a main that will make it work, it can be done with a temp dir for packaging process and then a save dialog for packager

**Comment by venomsOther** [comment]
This is now a part of #94 using electron packager is not going to work because there has to be a few steps in-between that occur that make this actually a very poor way to solve this issue. Also node has issues with copying asar files, so copying the electron binary contained in node_modules won't work and electron-downloader is too slow and obscure to make it package right.

**Comment by venomsOther** [comment]
The new idea is to implement it similar to chrome, it creates a link to the file that will spawn the native app with command line arguments

**Comment by venomsOther** [comment]
There are not ways with command line to create a link, but it can be done with vbs and maybe c++.

**Comment by venomsOther** [comment]
so maybe this would work as a child_process.exec
```
powershell "$s=(New-Object -COM WScript.Shell).CreateShortcut('%userprofile%\Start Menu\Programs\Startup\%~n0.lnk');$s.TargetPath='%~f0';$s.Save()"
```

**Comment by venomsOther** [comment]
powershell script that gets packaged with the app

**Comment by venomsOther** [comment]
the script would be like this
```
$WshShell = New-Object -comObject WScript.Shell
$Shortcut = $WshShell.CreateShortcut("$Home\Desktop\<WEBSITE_TITLE>.lnk")
$Shortcut.TargetPath = "C:\Program Files (x86)\Browserr/Browser.exe"
$Shortcut.Save()
```

```
'Set the additional parameters for the shortcut  
$Shortcut.Arguments = "/argument=value"  
```

**Comment by venomsOther** [comment]
> the script would be like this
> 
> ```
> $WshShell = New-Object -comObject WScript.Shell
> $Shortcut = $WshShell.CreateShortcut("$Home\Desktop\<WEBSITE_TITLE>.lnk")
> $Shortcut.TargetPath = "C:\Program Files (x86)\Browserr/Browser.exe"
> $Shortcut.Save()
> ```
> 
> ```
> 'Set the additional parameters for the shortcut  
> $Shortcut.Arguments = "/argument=value"  
> ```

That first section could be saved in a file ending in a .ps1 extension and will accept parameters from the first line

```
 param ( [string]$SourceExe, [string]$DestinationPath )
```
