### ISSUE TITLE
[FEATURE] command line options

### ISSUE THREAD

**Issue by eatmyvenom** [eatmyvenom/browserr#94]
## Current Behavior
Currently the applications behavior is to start the same way each time

## Wanted Behavior
What I would like to see is a set of command line options

```NodeJS version : 12.0.0; ElectronJS version : 5.0.1; Browserr version : 1.2.0;```

**Comment by venomsOther** [comment]
Issue is that when electron starts, it uses its own set of command line arguments that then is hidden from the app.

**Comment by venomsOther** [comment]
okay store process.argv in the main.js

**Comment by venomsOther** [comment]
then from the actual executer file, it has to route itself to app/node_modules/electron/dist/electron and then add command line arguments there instead of a npm start or something like that

**Comment by venomsOther** [comment]
then get it from `require('electron').remote.process.argv`

**Comment by eatmyvenom** [comment]
this needs a new binary so i am going to close this issue and the one about pkg sites
